apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_POSTGRES_URL
              value: jdbc:postgresql://my-db-test.io:5432/yourdbname
            - name: SPRING_POSTGRES_USERNAME
              value: myapplication
            - name: SPRING_POSTGRES_PASSWORD
              value: M3P@ssw0rd!
